language: java

notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget -nv http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar zxvf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/build-tools/17.0.0/
  - android list sdk
  - echo "y" | android -v update sdk --filter tools,build-tools-17.0.0,android-17 --no-ui --force 
